<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="11.3.7" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.3.7" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.3.7" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.3.7" />
    <PackageVersion Include="ReactiveUI.Avalonia" Version="11.3.0" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.7" />
    <PackageVersion Include="EvilBaschdi.About.Avalonia" Version="2025.5.11.19" />
    <PackageVersion Include="EvilBaschdi.Core.Avalonia" Version="2025.10.13.15" />
    <PackageVersion Include="EvilBaschdi.Core" Version="2025.9.16.16" />
    <PackageVersion Include="EvilBaschdi.Core.DependencyInjection" Version="2025.10.15.5" />
  </ItemGroup>
</Project>